### ISSUE TITLE
Would be cool to have on the event list a F or M and the age of the creator of the event. 

### ISSUE THREAD

**Issue by jpcandiotti** [pziegler/fitnessbuddy#12]
this will facilitate the moment to choose whether you prefer to join a male or a female, what do you think/.?

**Comment by pkishino** [comment]
i already fetch gender but age is quite restrictive via FB.. will have to check more

**Comment by jpcandiotti** [comment]
i mean Mor F at the event list information.

Date: Thu, 30 Apr 2015 03:14:07 -0700

**Comment by pkishino** [comment]
yeah, M or F is easy..age bit harder
