### ISSUE TITLE
Sharing the event on facebook

### ISSUE THREAD

**Issue by jpcandiotti** [pziegler/fitnessbuddy#16]
If i create an event on fitnessbuddy and then i want to make my friends on the area know about it, the facebook note realese shoud be something like : Hej! do you want to join my running this thursday at 18:00? . .. kind of .. we can speak about it

**Comment by pkishino** [comment]
yeah,thats what I wanted too but Facebook doesnt allow an app or so to fill in the note..user has to write it..ill look into it a bit more how one could do it

**Comment by jpcandiotti** [comment]
FACEBOOK ICON
